// Generated by CoffeeScript 1.4.0

/*
This is part of the Oblique AngularJS components
available at http://github.com/cwacek/Oblique
*/


(function() {
  var module;

  module = angular.module('oblique.directives', []);

  module.directive('autoComplete', function() {
    var settings;
    return settings = {
      restrict: 'A',
      link: function(scope, elem, attr) {
        var options;
        options = {
          source: scope.$eval(attr.autoComplete)
        };
        return elem.autocomplete(options);
      }
    };
  });

}).call(this);
